version: '3.8'

services:
  web:
    build:
      context: ./WEB
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - ./WEB:/usr/src/app
    environment:
      - NODE_ENV=development

# api-server:
#     build: ./api-server
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./api-server:/usr/src/app
#     environment:
#       - NODE_ENV=development

  # api:
  #   build:
  #     context: ./API
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   container_name: api
  #   restart: always
  #   environment:
  #     MONGO_URL: mongodb://mongo:27017/hap_db
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:4.2
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

# volumes:
#   mongo-data:
