[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "API"
[services.build]
builder = "nixpacks"
[services.deploy]
startCommand = "npm start"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
source = "WEB"
[services.build]
builder = "nixpacks"
[services.deploy]
startCommand = "npm run build && npm run serve"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
