/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAutocomplete: typeof import('./src/@core/components/AppAutocomplete.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppCombobox: typeof import('./src/@core/components/AppCombobox.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/components/AppDateTimePicker.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavigationBar: typeof import('./src/components/AppNavigationBar.vue')['default']
    AppSelect: typeof import('./src/@core/components/AppSelect.vue')['default']
    AppTextarea: typeof import('./src/@core/components/AppTextarea.vue')['default']
    AppTextField: typeof import('./src/@core/components/AppTextField.vue')['default']
    CustomCheckboxes: typeof import('./src/@core/components/CustomCheckboxes.vue')['default']
    CustomCheckboxesWithIcon: typeof import('./src/@core/components/CustomCheckboxesWithIcon.vue')['default']
    CustomCheckboxesWithImage: typeof import('./src/@core/components/CustomCheckboxesWithImage.vue')['default']
    CustomRadios: typeof import('./src/@core/components/CustomRadios.vue')['default']
    CustomRadiosWithIcon: typeof import('./src/@core/components/CustomRadiosWithIcon.vue')['default']
    CustomRadiosWithImage: typeof import('./src/@core/components/CustomRadiosWithImage.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
